### ISSUE TITLE
Sydney, AU group

### ISSUE THREAD

**Issue by thsutton** [type-theory/type-theory-study-group-2015#6]
We've started a group meeting in-person in Sydney. I'm not sure whether we'll be doing the same thing but at GMT+11 or if we'll diverge in content at some point.

Meetup page is here: http://www.meetup.com/Sydney-Type-Theory/ but I'm not sure if it should be listed in here? _A_ study group vs _this_ study group, etc.

**Comment by markfarrell** [comment]
Can add it here if you'd like. Perhaps under a "Local Chapters" section?
